USE ContainerStar;

CREATE TABLE dbo.Numbers
	(
	Id int NOT NULL IDENTITY (1, 1),
	NumberType smallint NOT NULL,
	CurrentNumber bigint NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Numbers ADD CONSTRAINT
	PK_Numbers PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
CREATE UNIQUE NONCLUSTERED INDEX IX_Number_Type ON dbo.Numbers
	(
	NumberType
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

INSERT INTO [dbo].[Numbers]
(NumberType, CurrentNumber)
SELECT 1, 10
UNION
SELECT 2, 345
UNION
SELECT 3, 488
